# @package _global_

model: transformer
bs: 64
hidden_dim: 128
num_embed: 256
embed_dim: 300
nhead: 100
num_layers: 6
encoder_path: checkpoints/vqvae_Encoder_epoch99_step51800.pth
quantize_path: checkpoints/vqvae_Quantize_epoch99_step51800.pth

